sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - "blead"         # builds perl from git
  - "blead-thr"
  - "dev"           # latest point release
  - "dev-thr"
  - "5.26"
  - "5.26-thr"
  - "5.24"
  - "5.24-thr"
  - "5.22"
  - "5.22-thr"
  - "5.20"
  - "5.20-thr"
  - "5.18"
  - "5.18-thr"
  - "5.16"
  - "5.16-thr"
  - "5.14"
  - "5.14-thr"
  - "5.12"
  - "5.12-thr"
  - "5.10"
  - "5.10-thr"
  - "5.8"
  - "5.8-thr"
  - "5.6.2"
  - "5.6.2-thr"
matrix:
  allow_failures:
    - perl: blead
    - perl: blead-thr
env:
  global:
    - AUTHOR_TESTING=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=0
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
